In [10]:
import numpy as np

def step_function(X):
    return np.where(X>=0,1,0)

X_and=np.array([[0,0],[0,1],[1,0],[1,1]])
Y_and=np.array([[0],[0],[0],[1]])
X_or=np.array([[0,0],[0,1],[1,0],[1,1]])
Y_or=np.array([[0],[1],[1],[1]])

class perceptron:

    def __init__(self,input_size,learning_rate=0.1,epochs=1000):
        self.weights=np.zeros((input_size,1))
        self.bias=0
        self.learning_rate=learning_rate
        self.epochs=epochs

    def train(self,X,Y):

        for _ in range(self.epochs):
            for inputs,label in zip(X,Y):
                inputs=inputs.reshape(-1,1)
                linear_output=np.dot(inputs.T,self.weights)+self.bias
                prediction=step_function(linear_output)
                error=label-prediction
                self.weights+=self.learning_rate*error*inputs
                self.bias+=self.learning_rate*error

    def predict(self,X):
        linear_output=np.dot(X,self.weights)+self.bias
        return step_function(linear_output)

perceptron_and=perceptron(input_size=2)
perceptron_and.train(X_and,Y_and)
perceptron_or=perceptron(input_size=2)
perceptron_or.train(X_or,Y_or)

print("AND function predictions:")
print(perceptron_and.predict(X_and))
print("OR function predictions:")
print(perceptron_or.predict(X_or))

and_test_input=np.array([[1,0]])
print("\n AND function Prediction for input [1,0]")
print(perceptron_and.predict(and_test_input))

or_test_input=np.array([[1,0]])
print("\n or function Prediction for input [1,0]")
print(perceptron_or.predict(or_test_input))

AND function predictions:
[[0]
 [0]
 [0]
 [1]]
OR function predictions:
[[0]
 [1]
 [1]
 [1]]

 AND function Prediction for input [1,0]
[[0]]

 or function Prediction for input [1,0]
[[1]]


In [11]:
import numpy as np

X_and = np.array([[0,0],[0,1],[1,0],[1,1]])
Y_and = np.array([[0],[0],[0],[1]])
X_or = np.array([[0,0],[0,1],[1,0],[1,1]])
Y_or = np.array([[0],[1],[1],[1]])

def step_function(X):
    return np.where(X>=0,1,0)

class perceptron:

    def __init__(self,input_size,learning_rate=0.1,epochs=1000):
        self.weights = np.zeros((input_size,1))
        self.bias = 0
        self.learning_rate = learning_rate
        self.epochs = epochs

    def train(self,X,Y):
        for i in range(self.epochs):
            for inputs,label in zip(X,Y):
                inputs=inputs.reshape(-1,1)
                linear_output = np.dot(inputs.T,self.weights)+self.bias
                prediction = step_function(linear_output)
                error = label-prediction
                self.weights += self.learning_rate * error *inputs 
                self.weights += self.learning_rate * error 

    def predict(self,X):
        linear_output = np.dot(X, self.weights)+self.bias
        return step_function(linear_output)
    
perceptron_and= perceptron(input_size = 2)
perceptron_and.train(X_and,Y_and)
perceptron_or= perceptron(input_size = 2)
perceptron_or.train (X_or,Y_or)

print(perceptron_and.predict(X_and))
print(perceptron_or.predict(X_or))

[[1]
 [1]
 [1]
 [1]]
[[1]
 [1]
 [1]
 [1]]
